version: '3.0'
services:
  rabbitmq:
    image: rabbitmq:3.12.9-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_PASS
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK_RELATIVE=0.8
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/20-mem.conf:/etc/rabbitmq/conf.d/20-mem.conf
    networks:
      - microservices-network


  postgres:
    image: postgres
    restart: always
    env_file: ./.env
    shm_size: 128mb
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - "5432:5432"
    networks:
      - microservices-network

  mysql:
    image: mysql:latest
    container_name: mysql-container2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - microservices-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - microservices-network


  openbakingroducer:
    depends_on:
      - postgres
      - rabbitmq
    build: ./openbankingproducer/openbanking
#    restart: on-failure
    env_file: ./.env
    ports:
      - "8020:8020"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/ms1
      - spring.datasource.driver-class-name=org.postgresql.Driver
      - spring.datasource.username=$POSTGRESDB_USER
      - spring.datasource.password=$POSTGRESDB_ROOT_PASSWORD
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect
    networks:
      - microservices-network
    command: ["--spring.datasource.driver-class-name=org.postgresql.Driver", "--spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL94Dialect"]

  transactioncons:
    depends_on:
      - mysql
      - rabbitmq
    build: ./openbankingconsumer/transaction
    restart: on-failure
    env_file: ./.env
    ports:
      - "8888:8888"
    environment:
      - spring.datasource.url= jdbc:mysql://mysql:3306/transactionbd?createDatabaseIfNotExist=TRUE
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100

    networks:
      - microservices-network


networks:
  microservices-network:
    driver: bridge

